version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/recipe_app/backend
    ports:
      - "8000:3000"
    depends_on:
      - db
  frontend:
    image: "node:10-alpine"
    user: "node"
    working_dir: /recipe_app/frontend
    volumes:
      - ./frontend:/recipe_app/frontend
    ports:
      - "3000:3000"
    command: "yarn start"
    depends_on:
      - backend
